config/routes.rb
Rails.application.routes.draw do
  # get 'orders/show'
  get 'users/show'
  get 'users/orders'
  devise_for :users
  # get 'publishers/index'
  # get 'publishers/show'
  # get 'genres/index'
  # get 'genres/show'
  # get 'platforms/show'
  # get 'platforms/index'
  # get 'products/index'
  # get 'products/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'products#index'

  resources :orders, only: [:show]

  resources :cart, only: [:create, :destroy]

  get 'cart/show'
  get 'cart/update_province', to: "cart#update_province", as: "cart_updated_province"

  resources :products, only: [:index, :show]
  # get "/products", to: "products#index", as: "products" #products_path
  # get "/products/:id", to: "products#show", as: "product" #product_path

  resources :platforms, only: [:index, :show]
  # get "/platforms", to: "platforms#index", as: "platforms" #platforms_path
  # get "/platforms/:id", to: "platforms#show", as: "platform" #platform_path

  resources :genres, only: [:index, :show]
  # get "/genres", to: "genres#index", as: "genres" #genres_path
  # get "/genres/:id", to: "genres#show", as: "genre" #genre_path

  resources :publishers, only: [:index, :show]
  # get "/publishers", to: "publishers#index", as: "publishers" #publishers_path
  # get "/publishers/:id", to: "publishers#show", as: "publisher" #publisher_path

  scope "/checkout" do
    post "create",  to: "checkout#create",  as: "checkout_create"
    get  "success", to: "checkout#success", as: "checkout_success"
    get  "cancel",  to: "checkout#cancel",  as: "checkout_cancel"
  end
end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :product_genres
  has_many :products, through: :product_genres
  validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :province
  has_many :product_orders
  has_many :products, through: :product_orders
  validates :order_no, presence: true, uniqueness: true
  validates :payment_amount_no_tax, :status, :payment_total, :pay_date, presence: true

  accepts_nested_attributes_for :product_orders, allow_destroy: true
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :product_platforms
  has_many :products, through: :product_platforms
  validates :name, presence: true, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :publisher
  has_many :product_platforms
  has_many :platforms, through: :product_platforms
  has_many :product_genres
  has_many :genres, through: :product_genres
  has_many :product_orders
  has_many :orders, through: :product_orders
  validates :name, :game_id, presence: true, uniqueness: true
  validates :price, numericality: true
  has_one_attached :image

  accepts_nested_attributes_for :product_genres, allow_destroy: true
  accepts_nested_attributes_for :product_platforms, allow_destroy: true
end

app/models/product_genre.rb
class ProductGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :product
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, :price, presence: true
end

app/models/product_platform.rb
class ProductPlatform < ApplicationRecord
  belongs_to :platform
  belongs_to :product
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
  validates :name, presence: true, uniqueness: true
  validates :HST, :GST, :PST, presence: true
  has_many :users
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :products
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :user_name, presence: true, uniqueness: true
  belongs_to :province
  has_many :orders
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  # POST /cart
  # Data sent as form data (params)
  def create
    # the logger will show in the rails server.. super useful for debugging!!
    product_id = params[:id].to_i
    quantity = params[:quantity].to_i

    logger.debug("Adding #{product_id} to cart.")
    product = Product.find(product_id)

    session[:shopping_cart][product_id] = quantity

    flash[:notice] = ["➕#{quantity} #{'copy'.pluralize(quantity)} of #{product.name} #{quantity > 1 ? 'are' : 'is'} in the cart.", -2]

    redirect_back(fallback_location: root_path)
  end

  # DELETE /cart/:id
  def destroy
    # removes params[:id] from cart
    logger.debug("Removing #{params[:id]} from cart.")
    id = params[:id]
    session[:shopping_cart].delete(id)
    product = Product.find(id)
    flash[:notice] = ["➖ #{product.name} removed from cart.", -2]
    redirect_back(fallback_location: root_path)
  end

  def show
    @products = Product.find(session[:shopping_cart].keys)
    @cart = session[:shopping_cart]
    @cart_province = session[:cart_province]["id"]
    cart_province = session[:cart_province]
    @gst = (cart_province["GST"].to_f / 100).round(2)
    @pst = (cart_province["PST"].to_f / 100).round(2)
    @hst = (cart_province["HST"].to_f / 100).round(2)
    subtotal_all_products = 0

    @products.each do |product|
      subtotal = product.price * @cart["#{product.id}"]
      subtotal_all_products += subtotal
    end

    # Calculate total
    @gst_amount = subtotal_all_products * @gst.round(2)
    @hst_amount = subtotal_all_products * @hst.round(2)
    @pst_amount = subtotal_all_products * @pst.round(2)
    @total = (subtotal_all_products + @gst_amount + @hst_amount + @pst_amount).round(2)
    @subtotal_all_products = subtotal_all_products
  end

  def update_province
    province_id = params[:id]["province_id"]

    if(province_id != 0 && province_id != nil)
      session[:cart_province] = Province.find(province_id.to_i)
    end
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart/show.html.erb
<h1>Cart</h1>

<% if @products.count != 0 %>
  <table>
    <tr>
      <td></td>
      <th>Product Title</th>
      <th>Price</th>
      <th>Quantity</th>
      <td></td><td></td>
      <th>Subtotal</th>
      <% if @gst != 0 %>
        <th>GST</th>
      <% end %>
      <% if @hst != 0 %>
        <th>HST</th>
      <% end %>
      <% if @pst != 0 %>
        <th>PST</th>
      <% end %>

    </tr>
    <% @products.each do |product| %>
      <% subtotal = product.price * @cart["#{product.id}"] %>
      <tr>
        <td><%= link_to '❌', cart_path(product), method: :delete %></td>
        <td><%= link_to product.name, product %></td>
        <td><%= product.price %></td>
        <td><%= @cart["#{product.id}"] %></td> <!-- Quantity -->
        <td>
          <%= form_with  url: cart_index_path, method: :post do %>
            <%= hidden_field_tag(:id, product.id) %>
            <%= hidden_field_tag(:quantity, @cart["#{product.id}"] + 1) %>
            <% if cart.include?(product) %>
              <%= button_tag '➕' %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= form_with  url: cart_index_path, method: :post do %>
            <%= hidden_field_tag(:id, product.id) %>
            <%= hidden_field_tag(:quantity, @cart["#{product.id}"] - 1) %>
            <% if @cart["#{product.id}"] > 1 %>
              <%= button_tag '➖' %>
            <% end %>
          <% end %>
        </td>
        <td><%= (subtotal).round(2) %></td>
        <% if @products.count == 1%>
          <% if @gst != 0 %>
            <td><%= (@subtotal_all_products * @gst).round(2) %></td>
          <% end %>
          <% if @hst != 0 %>
            <td><%= (@subtotal_all_products * @hst).round(2) %></td>
          <% end %>
          <% if @pst != 0 %>
            <td><%= (@subtotal_all_products * @pst).round(2) %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
    <tr>
      <% if @products.count > 1%>
        <td></td><td></td><td></td>
        <td></td><td></td><td></td><td> <%= @subtotal_all_products.round(2) %></td>
        <% if @gst != 0 %>
          <td><%= (@subtotal_all_products * @gst).round(2) %></td>
        <% end %>
        <% if @hst != 0 %>
          <td><%= (@subtotal_all_products * @hst).round(2) %></td>
        <% end %>
        <% if @pst != 0 %>
          <td><%= (@subtotal_all_products * @pst).round(2) %></td>
        <% end %>
      <% end %>
    </tr>
  </table>
  <hr>
  <h3>Total: <%= number_to_currency(@total) %></h3>

  <div id="update province">
    <%= form_with(url: cart_updated_province_path, method: :get, local: true) do %>
    <label>Province: </label>
    <%= collection_select(:id, :province_id, Province.all, :id, :name, selected: @cart_province)  %>
    <%= submit_tag("Update", class: "button is-primary") %>
    <% end %>
  </div>

  <% if current_user != nil %>

    <%= form_with url: checkout_create_path, remote: true do %>
      <div id="address_label">
        <label for="address">Ship To: </label>
        <%= text_field_tag(:address, nil, class: "input", value: current_user.address) %></div>
      <div id="Postal_code_label">
        <label for="postal_code">Postal Code:</label>
        <%= text_field_tag(:postal_code, nil, class: "input", value: current_user.postal_code) %>
      </div>
      <%= hidden_field_tag(:total, @total) %>
      <%= hidden_field_tag(:subtotal, @subtotal_all_products) %>
      <%= hidden_field_tag(:products, @products.pluck(:id)) %>
      <%= hidden_field_tag(:gst, @gst_amount) %>
      <%= hidden_field_tag(:hst, @hst_amount) %>
      <%= hidden_field_tag(:pst, @pst_amount) %>
      <%= button_tag 'Checkout' %>
    <% end %>
  <% else %>
    <h2>Please <%= link_to 'Sign In', new_user_session_path %> or <%= link_to 'Sign Up', new_user_registration_path %> to check out your items.</h2>
  <% end %>

<% else %>
  <h3>There are no products in your cart. Get Shopping!</h3>
<% end %>