config/routes.rb
Rails.application.routes.draw do
  # get 'orders/show'
  get 'users/show'
  get 'users/orders'
  devise_for :users
  # get 'publishers/index'
  # get 'publishers/show'
  # get 'genres/index'
  # get 'genres/show'
  # get 'platforms/show'
  # get 'platforms/index'
  # get 'products/index'
  # get 'products/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'products#index'

  resources :orders, only: [:show]

  resources :cart, only: [:create, :destroy]

  get 'cart/show'
  get 'cart/update_province', to: "cart#update_province", as: "cart_updated_province"

  resources :products, only: [:index, :show]
  # get "/products", to: "products#index", as: "products" #products_path
  # get "/products/:id", to: "products#show", as: "product" #product_path

  resources :platforms, only: [:index, :show]
  # get "/platforms", to: "platforms#index", as: "platforms" #platforms_path
  # get "/platforms/:id", to: "platforms#show", as: "platform" #platform_path

  resources :genres, only: [:index, :show]
  # get "/genres", to: "genres#index", as: "genres" #genres_path
  # get "/genres/:id", to: "genres#show", as: "genre" #genre_path

  resources :publishers, only: [:index, :show]
  # get "/publishers", to: "publishers#index", as: "publishers" #publishers_path
  # get "/publishers/:id", to: "publishers#show", as: "publisher" #publisher_path

  scope "/checkout" do
    post "create",  to: "checkout#create",  as: "checkout_create"
    get  "success", to: "checkout#success", as: "checkout_success"
    get  "cancel",  to: "checkout#cancel",  as: "checkout_cancel"
  end
end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :product_genres
  has_many :products, through: :product_genres
  validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :province
  has_many :product_orders
  has_many :products, through: :product_orders
  validates :order_no, presence: true, uniqueness: true
  validates :payment_amount_no_tax, :status, :payment_total, :pay_date, presence: true

  accepts_nested_attributes_for :product_orders, allow_destroy: true
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :product_platforms
  has_many :products, through: :product_platforms
  validates :name, presence: true, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :publisher
  has_many :product_platforms
  has_many :platforms, through: :product_platforms
  has_many :product_genres
  has_many :genres, through: :product_genres
  has_many :product_orders
  has_many :orders, through: :product_orders
  validates :name, :game_id, presence: true, uniqueness: true
  validates :price, numericality: true
  has_one_attached :image

  accepts_nested_attributes_for :product_genres, allow_destroy: true
  accepts_nested_attributes_for :product_platforms, allow_destroy: true
end

app/models/product_genre.rb
class ProductGenre < ApplicationRecord
  belongs_to :genre
  belongs_to :product
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, :price, presence: true
end

app/models/product_platform.rb
class ProductPlatform < ApplicationRecord
  belongs_to :platform
  belongs_to :product
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
  validates :name, presence: true, uniqueness: true
  validates :HST, :GST, :PST, presence: true
  has_many :users
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :products
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :user_name, presence: true, uniqueness: true
  belongs_to :province
  has_many :orders
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PingdomGames</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 style="font-style:italic">
      <div class="title">
        <%= image_tag("logos/transparent_logo.png", width: '100px') %>
        Pingdom Games
      </div>
    </h1>

    <!--<%= debug cart %>-->

    <ul>
      <% if user_signed_in? %>
        <li><%= link_to "Hi, #{current_user.user_name}", users_show_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <% end %>
    </ul>

    <details>
      <summary>
          <%= link_to image_tag("cart.jpg", width:60), cart_show_path %>
          Cart
          <% if cart.present? %>
            <sup><%= cart.size %></sup>
          <% end %>
      </summary>
      <% if cart.present? %>
        <ul>
          <% cart.each do |product| %>
            <li>
              <%= session[:shopping_cart]["#{product.id}"] %> X <%= link_to product.name, product %> <%= link_to '❌', cart_path(product), method: :delete %>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>No items in your cart.</p>
      <% end %>
    </details>

    <nav>
      <%= link_to 'Games', products_path %>
      <%= link_to 'Consoles', platforms_path %>
      <%= link_to 'Genres', genres_path %>
      <%= link_to 'Publishers', publishers_path %>

      <div id="Search_Form">
        <%= form_with(url: products_path, method: :get, local: true) do %>
        <%= text_field_tag(:keywords, nil, class: "input", placeholder: "Search for Games") %>
        <%= select_tag 'platform', options_for_select(["Console"] + Platform.all.map{|p| [p.name, p.id]}) %>
        <%= submit_tag("Search", class: "button is-primary") %>
        <% end %>
      </div>
    </nav>
    <hr>

    <% if flash[:notice] && (!current_page?('/cart/show') || flash[:notice][1] == -1) %>
      <% if flash[:notice][1] == -1 || flash[:notice][1] == -2 %>
        <p><%= flash[:notice][0] %></p>
      <% else %>
        <p><%= flash[:notice] %></p>
      <% end %>
      <hr>
    <% end %>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <footer>
      <hr>
      <p>2021 Pingom Games Co</p>
    </footer>
  </body>
</html>